# Site settings
title: K0HAX Github Site
description: > # this means to ignore newlines until "baseurl:"
    This is Mikey's github site! Welcome.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://k0hax.github.io" # the base hostname & protocol for your site
twitter_username: K0HAX
github_username:  k0hax

# Build settings
markdown: kramdown
